version: "3.8"
services:
  FB_envtest:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: Dockerfile 

    tty: true 
    image: fb_envtest_image
    container_name: fb_envtest_container
    volumes:
      - ./:/app