version: "3.7"
services:
  FB_envtest:
    build:
      context: ./
      dockerfile: Dockerfile 

    tty: true 
    image: fb_envtest_image
    container_name: fb_envtest_container
    volumes:
      - ./:/app